# Generated by Django 6.0.4 on 2026-04-11 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('overview', models.TextField()),
                ('long_description', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('devStory', models.TextField(blank=True)),
                ('demoUrl', models.URLField(blank=True)),
                ('githubUrl', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived'), ('draft', 'Draft'), ('idea', 'idea')], default='in-progress', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('featured', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('project_images', models.ManyToManyField(to='projects.projectimages')),
                ('tags', models.ManyToManyField(to='projects.tag')),
                ('technologies', models.ManyToManyField(to='projects.technology')),
            ],
        ),
    ]
