# Generated by Django 6.0.4 on 2026-04-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_images',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='kuda', upload_to='project_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
