# Generated by Django 6.0.4 on 2026-04-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
